name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: pnpm install & test
        run: |
          pnpm install --frozen-lockfile
          pnpm test

  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: pnpm install & build
        run: |
          pnpm install --frozen-lockfile
          pnpm build
